{
 "title": "All sensors dashboard",
 "time": { "from": "2004-07-17T10:00:00.000Z", "to": "2004-07-18T10:00:00.000Z" },
 "panels": [
  {
   "title": "System Overview",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN topic = 't' THEN 'Temperature'\r\n    WHEN topic = 'rh' THEN 'Humidity'\r\n    WHEN topic = 'ah' THEN 'Absolute Humidity'\r\n    WHEN topic = 'co_gt' THEN 'Carbon Monoxide (CO)'\r\n    WHEN topic = 'c6h6_gt' THEN 'Benzene (C6H6)'\r\n    WHEN topic = 'nmhc_gt' THEN 'NMHC'\r\n    WHEN topic = 'no2_gt' THEN 'Nitrogen Dioxide (NO2)'\r\n    WHEN topic = 'nox_gt' THEN 'Nitrogen Oxides (NOx)'\r\n    WHEN topic = 'pt08_s1_co' THEN 'Tin Oxide (CO)'\r\n    WHEN topic = 'pt08_s2_nmhc' THEN 'Titania (NMHC)'\r\n    WHEN topic = 'pt08_s3_nox' THEN 'Tungsten Oxide (NOx)'\r\n    WHEN topic = 'pt08_s4_no2' THEN 'Tungsten Oxide (NO2)'\r\n    WHEN topic = 'pt08_s5_o3' THEN 'Indium Oxide (O3)'\r\n    ELSE topic \r\n  END as topic, \r\n  value\r\nFROM environment\r\nWHERE $__timeFilter(time)\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Sensors by Anomaly Count",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n    CASE \r\n    WHEN topic = 't' THEN 'Temperature'\r\n    WHEN topic = 'rh' THEN 'Humidity'\r\n    WHEN topic = 'ah' THEN 'Absolute Humidity'\r\n    WHEN topic = 'co_gt' THEN 'Carbon Monoxide (CO)'\r\n    WHEN topic = 'c6h6_gt' THEN 'Benzene (C6H6)'\r\n    WHEN topic = 'nmhc_gt' THEN 'NMHC'\r\n    WHEN topic = 'no2_gt' THEN 'Nitrogen Dioxide (NO2)'\r\n    WHEN topic = 'nox_gt' THEN 'Nitrogen Oxides (NOx)'\r\n    WHEN topic = 'pt08_s1_co' THEN 'Tin Oxide (CO)'\r\n    WHEN topic = 'pt08_s2_nmhc' THEN 'Titania (NMHC)'\r\n    WHEN topic = 'pt08_s3_nox' THEN 'Tungsten Oxide (NOx)'\r\n    WHEN topic = 'pt08_s4_no2' THEN 'Tungsten Oxide (NO2)'\r\n    WHEN topic = 'pt08_s5_o3' THEN 'Indium Oxide (O3)'\r\n    ELSE topic \r\n  END  as \"Sensor Name\",\r\n  value as \"Total Anomalies\"\r\nFROM anomaly\r\nWHERE global = 1 \r\n  AND $__timeFilter(time)\r\nORDER BY value DESC"
    }
   ]
  },
  {
   "title": "Anomaly Matrix",
   "type": "status-history",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, topic, global, local\r\nFROM anomaly\r\nWHERE $__timeFilter(time) \r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Global Trends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, topic, mean\r\nFROM moving_statistics\r\nWHERE $__timeFilter(time)\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Weather Dynamics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  time,\r\n  value as 'Temperature (°C)'\r\nFROM environment\r\nWHERE \r\n  topic = 't'\r\n  AND $__timeFilter(time)\r\nORDER BY time ASC"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  time,\r\n  value as 'Rel. Humidity (%)'\r\nFROM environment\r\nWHERE \r\n  topic = 'rh'\r\n  AND $__timeFilter(time)\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Temperature vs Rel. Humidity",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 23 },
   "options": {
    "content": "This chart demonstrates the natural inverse relationship between ambient temperature and relative humidity. Typically, as air temperature rises during the day, the relative humidity drops and vice versa.\nDivergences from this pattern may indicate weather fronts or sensor anomalies."
   }
  },
  {
   "title": "Direct Source Correlation",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 33 },
   "options": {
    "content": "This chart shows the linear relationship between CO and NOx levels. Since both pollutants are primarily emitted by combustion engines (traffic), they rise and fall together instantly."
   }
  },
  {
   "title": "Carbon Monoxide and Nitrogen Oxides relationship",
   "type": "xychart",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 33 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  time,\r\n  MAX(CASE WHEN topic = 'co_gt' THEN value END) as \"Carbon Monoxide (CO)\",\r\n  MAX(CASE WHEN topic = 'nox_gt' THEN value END) as \"Nitrogen Oxides (NOx)\"\r\nFROM environment\r\nWHERE \r\n  (topic = 'co_gt' OR topic = 'nox_gt')\r\n  AND value != -200  -- Hibaszűrés\r\n  AND $__timeFilter(time)\r\nGROUP BY time\r\nHAVING \r\n  MAX(CASE WHEN topic = 'co_gt' THEN value END) IS NOT NULL \r\n  AND \r\n  MAX(CASE WHEN topic = 'nox_gt' THEN value END) IS NOT NULL"
    }
   ]
  }
 ]
}