{
 "title": "Anomaly Inspector (Evaluation) 2",
 "time": { "from": "2004-07-01T13:30:00.000Z", "to": "2004-08-13T21:30:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "Carbon Monoxide (CO) : pt08_s1_co, Non Metanic Hydrocarbons (NMHC) : pt08_s2_nmhc, Total Nitrogen Oxides (NOx) : pt08_s3_nox, Nitrogen Dioxide (NO2) : pt08_s4_no2, Ozone (O3) : pt08_s5_o3, Temperature : t, Absolute Humidity : ah, Relative Humidity : rh"
   }
  ]
 },
 "panels": [
  {
   "title": "Global abnormality detector performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Sensor readings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, CASE WHEN value = -200 THEN NULL ELSE value END as value\nFROM environment\nWHERE topic = '$topic'\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value\nFROM anomaly\nWHERE topic = '$topic'\n  AND global = 1\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value\nFROM anomaly\nWHERE topic = '$topic'\n  AND global = 1\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, cast(value as BOOLEAN) as true_label\nFROM true_labels\n  WHERE topic = '$topic'\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    }
   ]
  },
  {
   "title": "Labeled anomalies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, topic\nFROM true_labels\nWHERE topic = '$topic'\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    }
   ]
  },
  {
   "title": "Detected abnormalities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value\nFROM anomaly\nWHERE topic = '$topic'\n  AND global = 1\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    }
   ]
  },
  {
   "title": "Recalling labeled anomalies",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT COUNT(a.time) AS true_positive\nFROM anomaly a\nJOIN true_labels l\n  ON a.time = l.time\nWHERE l.topic = '$topic'\n  AND a.topic = '$topic'\n  AND a.global = 1\n  AND a.time >= $__timeFrom() AND a.time <= $__timeTo()"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT COUNT(a.time) AS false_positive\nFROM anomaly a\nWHERE a.topic = '$topic'\n  AND a.time >= $__timeFrom() AND a.time <= $__timeTo()\n  AND a.global = 1\n  AND a.time NOT IN (\n    SELECT l.time\n    FROM true_labels l\n    WHERE l.topic = '$topic'\n  )"
    }
   ]
  },
  {
   "title": "Local abnormality detector performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Sensor readings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, CASE WHEN value = -200 THEN NULL ELSE value END as value\nFROM environment\nWHERE topic = '$topic'\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value\nFROM anomaly\nWHERE topic = '$topic'\n  AND local = 1\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value\nFROM anomaly\nWHERE topic = '$topic'\n  AND local = 1\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, cast(value as BOOLEAN) as true_label\nFROM true_labels\n  WHERE topic = '$topic'\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    }
   ]
  },
  {
   "title": "Labeled anomalies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, topic\nFROM true_labels\nWHERE topic = '$topic'\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    }
   ]
  },
  {
   "title": "Detected abnormalities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, value\nFROM anomaly\nWHERE topic = '$topic'\n  AND local = 1\n  AND time >= $__timeFrom() AND time <= $__timeTo();"
    }
   ]
  },
  {
   "title": "Recalling labeled anomalies",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT COUNT(a.time) AS true_positive\nFROM anomaly a\nJOIN true_labels l\n  ON a.time = l.time\nWHERE l.topic = '$topic'\n  AND a.topic = '$topic'\n  AND a.local = 1\n  AND a.time >= $__timeFrom() AND a.time <= $__timeTo()"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT COUNT(a.time) AS false_positive\nFROM anomaly a\nWHERE a.topic = '$topic'\n  AND a.time >= $__timeFrom() AND a.time <= $__timeTo()\n  AND a.local = 1\n  AND a.time NOT IN (\n    SELECT l.time\n    FROM true_labels l\n    WHERE l.topic = '$topic'\n  )"
    }
   ]
  }
 ]
}