{
 "title": "Anomaly Inspector",
 "time": { "from": "2004-07-01T00:00:00.000Z", "to": "2004-07-31T16:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "Carbon Monoxide (CO) : pt08_s1_co, Non Metanic Hydrocarbons (NMHC) : pt08_s2_nmhc, Total Nitrogen Oxides (NOx) : pt08_s3_nox, Nitrogen Dioxide (NO2) : pt08_s4_no2, Ozone (O3) : pt08_s5_o3, Temperature : t, Absolute Humidity : ah, Relative Humidity : rh"
   }
  ]
 },
 "panels": [
  {
   "title": "Sensor readings",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, CASE WHEN CAST(value as DOUBLE) = -200 THEN NULL ELSE CAST(value as DOUBLE) END as value\nFROM environment\nWHERE topic = '$topic';"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, CAST(value as DOUBLE)\nFROM anomaly\nWHERE topic = '$topic';"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, CAST(value as DOUBLE) as missing_value\nFROM anomaly\nWHERE topic = '$topic'\n  AND missing"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, CAST(value as DOUBLE) as global_anomaly\nFROM anomaly\nWHERE topic = '$topic'\n  AND global"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, CAST(value as DOUBLE) as local_anomaly\nFROM anomaly\nWHERE topic = '$topic'\n  AND local"
    }
   ]
  },
  {
   "title": "Total abnormalities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, CAST(value as DOUBLE)\nFROM anomaly\nWHERE topic = '$topic';"
    }
   ]
  },
  {
   "title": "Recent anomalies",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "select time, value\nfrom anomaly\nwhere topic = '$topic'\norder by time desc"
    }
   ]
  }
 ]
}