{
 "title": "Forecasting (Evaluation)",
 "time": { "from": "2004-03-31T22:00:00.000Z", "to": "2004-04-18T21:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "Carbon Monoxide (CO) : pt08_s1_co, Non Metanic Hydrocarbons (NMHC) : pt08_s2_nmhc, Total Nitrogen Oxides (NOx) : pt08_s3_nox, Nitrogen Dioxide (NO2) : pt08_s4_no2, Ozone (O3) : pt08_s5_o3, Temperature : t, Absolute Humidity : ah, Relative Humidity : rh"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance Metrics (Online)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    time,\n    -- Absolute Error (AE)\n    ABS(online_pred - value) AS abs_error,\n \n    -- Cumulative Mean Absolute Error (MAE)\n    AVG(ABS(online_pred - value)) OVER (\n        PARTITION BY topic\n        ORDER BY time\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS mae_cummulative,\n \n    -- Squared Error (SE)\n    POWER(online_pred - value, 2) AS squared_error,\n \n    -- Cumulative RMSE\n    SQRT(\n        AVG(POWER(online_pred - value, 2)) OVER (\n            PARTITION BY topic\n            ORDER BY time\n            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n        )\n    ) AS rmse_cummulative,\n \n    -- Cumulative Bias (mean signed error)\n    AVG(online_pred - value) OVER (\n        PARTITION BY topic\n        ORDER BY time\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS bias_cummulative\n \nFROM environment\nWHERE topic = '$topic' AND $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Performance Metrics (H1)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    time,\n    -- Absolute Error (AE)\n    ABS(`pred_H1` - value) AS abs_error,\n \n    -- Cumulative Mean Absolute Error (MAE)\n    AVG(ABS(`pred_H1` - value)) OVER (\n        PARTITION BY topic\n        ORDER BY time\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS mae_cummulative,\n \n    -- Squared Error (SE)\n    POWER(`pred_H1` - value, 2) AS squared_error,\n \n    -- Cumulative RMSE\n    SQRT(\n        AVG(POWER(`pred_H1` - value, 2)) OVER (\n            PARTITION BY topic\n            ORDER BY time\n            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n        )\n    ) AS rmse_cummulative,\n \n    -- Cumulative Bias (mean signed error)\n    AVG(`pred_H1` - value) OVER (\n        PARTITION BY topic\n        ORDER BY time\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS bias_cummulative\n \nFROM environment\nWHERE topic = '$topic' AND $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Performance Metrics (H2)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    time,\n    -- Absolute Error (AE)\n    ABS(`pred_H2` - value) AS abs_error,\n \n    -- Cumulative Mean Absolute Error (MAE)\n    AVG(ABS(`pred_H2` - value)) OVER (\n        PARTITION BY topic\n        ORDER BY time\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS mae_cummulative,\n \n    -- Squared Error (SE)\n    POWER(`pred_H2` - value, 2) AS squared_error,\n \n    -- Cumulative RMSE\n    SQRT(\n        AVG(POWER(`pred_H2` - value, 2)) OVER (\n            PARTITION BY topic\n            ORDER BY time\n            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n        )\n    ) AS rmse_cummulative,\n \n    -- Cumulative Bias (mean signed error)\n    AVG(`pred_H2` - value) OVER (\n        PARTITION BY topic\n        ORDER BY time\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS bias_cummulative\n \nFROM environment\nWHERE topic = '$topic' AND $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Performance Metrics (H3)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n    time,\n    -- Absolute Error (AE)\n    ABS(`pred_H3` - value) AS abs_error,\n \n    -- Cumulative Mean Absolute Error (MAE)\n    AVG(ABS(`pred_H3` - value)) OVER (\n        PARTITION BY topic\n        ORDER BY time\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS mae_cummulative,\n \n    -- Squared Error (SE)\n    POWER(`pred_H3` - value, 2) AS squared_error,\n \n    -- Cumulative RMSE\n    SQRT(\n        AVG(POWER(`pred_H3` - value, 2)) OVER (\n            PARTITION BY topic\n            ORDER BY time\n            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n        )\n    ) AS rmse_cummulative,\n \n    -- Cumulative Bias (mean signed error)\n    AVG(`pred_H3` - value) OVER (\n        PARTITION BY topic\n        ORDER BY time\n        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n    ) AS bias_cummulative\n \nFROM environment\nWHERE topic = '$topic' AND $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Prediction history",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time,\n    CASE WHEN value = -200 THEN NULL ELSE value END AS value,\n    online_pred,\n    `pred_H1`,\n    `pred_H2`,\n    `pred_H3`\nFROM environment\nWHERE topic = '$topic'\nAND $__timeFilter(time)"
    }
   ]
  }
 ]
}