{
 "title": "Dashboard v1",
 "time": { "from": "2004-07-16T04:00:00.000Z", "to": "2004-07-16T12:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "Carbon Monoxide (CO) : pt08_s1_co, Non Metanic Hydrocarbons (NMHC) : pt08_s2_nmhc, Total Nitrogen Oxides (NOx) : pt08_s3_nox, Nitrogen Dioxide (NO2) : pt08_s4_no2, Ozone (O3) : pt08_s5_o3, Temperature : t, Absolute Humidity : ah, Relative Humidity : rh"
   }
  ]
 },
 "panels": [
  {
   "title": "Live Sensor Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "SELECT last(\"value\") FROM \"environment\" WHERE $timeFilter GROUP BY \"topic\"",
     "rawSql": "SELECT value as \"${topic} Current Value\"\r\nFROM environment\r\nWHERE topic = '$topic' AND $__timeFilter(time) \r\nORDER BY time DESC\r\nLIMIT 1"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT sqrt(variance) as \"${topic} Volatility\"\r\nFROM moving_statistics\r\nWHERE topic = '$topic' AND $__timeFilter(time) \r\nORDER BY time DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Total Anomalies Detected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "SELECT Count(value) FROM \"anomaly\"",
     "rawSql": "SELECT COUNT(*) as \"Number of Anomalies\"\r\nFROM anomaly\r\nWHERE topic = '$topic'\r\n  AND (global = 1 OR local = 1)\r\n  AND $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "candlestick",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  q1 as \"open\",\r\n  q3 as \"close\",\r\n  min as \"low\",\r\n  max as \"high\"\r\nFROM quantiles\r\nWHERE topic = '$topic'\r\n  AND $__timeFilter(time)\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Sensor readings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  CASE WHEN value = -200 THEN NULL ELSE value END as \"Sensor value\"\r\nFROM environment\r\nWHERE topic = '$topic' AND $__timeFilter(time)\r\nORDER BY time ASC"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  0 as \"Missing Marker\"\r\nFROM anomaly\r\nWHERE topic = '$topic' AND missing = 1 AND $__timeFilter(time)"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  value as \"Global Marker\"\r\nFROM anomaly\r\nWHERE topic = '$topic' AND global = 1 AND $__timeFilter(time)"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  value as \"Local Marker\"\r\nFROM anomaly\r\nWHERE topic = '$topic' AND local = 1 AND $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Forecasts vs Actual data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Recent Data Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  e.topic,\r\n  e.time,\r\n  e.value,\r\n  COALESCE((a.global = 1 OR a.local = 1 OR a.missing = 1), false) as abnormal\r\nFROM environment e\r\nLEFT JOIN anomaly a\r\n  ON e.time = a.time AND e.topic = a.topic\r\nWHERE\r\n  e.topic = '$topic' AND $__timeFilter(e.time)\r\nORDER BY\r\n  e.time DESC"
    }
   ]
  },
  {
   "title": "Safe Zone",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 19 },
   "targets": [
    {
     "dataset": "iox",
     "query": "SELECT   time,   value\nFROM environment\nWHERE topic = '$topic'\nORDER BY time ASC",
     "rawSql": "SELECT\r\n  time,\r\n  value\r\nFROM environment\r\nWHERE topic = '$topic' AND $__timeFilter(time)\r\nORDER BY time ASC"
    },
    {
     "dataset": "iox",
     "query": "SELECT   time,   q1 as \"Lower Bound\",   q3 as \"Upper Bound\"\nFROM quantiles\nWHERE topic = '$topic'\nORDER BY time ASC",
     "rawSql": "SELECT\r\n  time,\r\n  q1 as \"Lower Bound\",\r\n  q3 as \"Upper Bound\"\r\nFROM quantiles\r\nWHERE topic = '$topic' AND $__timeFilter(time)\r\nORDER BY time ASC"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT value\r\nFROM anomaly\r\nWHERE topic = '$topic'\r\n  AND (global = 1 OR local = 1)\r\n  AND $__timeFilter(time)"
    }
   ]
  }
 ]
}