{
 "title": "Dashboard v1",
 "time": { "from": "2004-08-01T10:00:00.000Z", "to": "2004-08-01T14:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "co_gt, nox_gt, no2_gt, ah, rh, t, c6h6_gt"
   }
  ]
 },
 "panels": [
  {
   "title": "Live Sensor Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 23, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"environment\" WHERE $timeFilter GROUP BY \"topic\""
    }
   ]
  },
  {
   "title": "Real-time Sensor Readings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Actual Value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"environment\" WHERE \"topic\" = '$topic' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Anomaly Detected",
     "query": "SELECT \"value\" FROM \"anomaly\" WHERE \"topic\" = '$topic' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Anomalies Detected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"anomaly\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Recent Data Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "Value",
     "query": "SELECT \"value\" FROM \"environment\" WHERE \"topic\" = '$topic' AND $timeFilter"
    },
    {
     "alias": "Forecast Value",
     "query": "SELECT \"value\" FROM \"forecasts\" WHERE \"topic\" = '$topic' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Forecast vs Actual Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Ground Truth",
     "query": "SELECT \"value\" FROM \"environment\" WHERE \"topic\" = '$topic' AND $timeFilter"
    },
    {
     "alias": "Forcast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"forecasts\" WHERE \"topic\" = '$topic' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}