{
 "title": "New dashboard",
 "time": { "from": "2004-07-13T11:39:38.161Z", "to": "2004-07-18T18:48:07.309Z" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "Carbon Monoxide (CO) : pt08_s1_co, Non Metanic Hydrocarbons (NMHC) : pt08_s2_nmhc, Total Nitrogen Oxides (NOx) : pt08_s3_nox, Nitrogen Dioxide (NO2) : pt08_s4_no2, Ozone (O3) : pt08_s5_o3, Temperature : t, Absolute Humidity : ah, Relative Humidity : rh"
   }
  ]
 },
 "panels": [
  {
   "title": "Trend detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  time,\r\n  value AS Trend_increase_detection\r\nFROM trend\r\nWHERE \r\n  time >= $__timeFrom() AND \r\n  time <= $__timeTo() AND\r\n  time >= '2004-01-01T00:00:00Z' AND\r\n  \"value\" != -200 AND\r\n  \"type\" = 1 AND \r\n  topic = '$topic'\r\nORDER BY time;\r\n"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  time,\r\n  value AS original_value\r\nFROM trend\r\nWHERE \r\n  time >= $__timeFrom() AND \r\n  time <= $__timeTo() AND\r\n  time >= '2004-01-01T00:00:00Z' AND\r\n  \"value\" != -200 AND\r\n  topic = '$topic'\r\n"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  time,\r\n  value AS Trend_decrease_detection\r\nFROM trend\r\nWHERE \r\n  time >= $__timeFrom() AND \r\n  time <= $__timeTo() AND\r\n  time >= '2004-01-01T00:00:00Z' AND\r\n  \"value\" != -200 AND\r\n  \"type\" = -1 AND \r\n  topic = '$topic'\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Exponential Moving standard deviation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, sqrt(variance)AS STD FROM \"moving_statistics\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND topic = '$topic'"
    }
   ]
  },
  {
   "title": "Exponential Moving standard deviation",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, sqrt(variance) AS std FROM \"moving_statistics\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND topic = '$topic'"
    }
   ]
  },
  {
   "title": "Exponential Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, mean FROM \"moving_statistics\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND topic = '$topic'"
    }
   ]
  },
  {
   "title": "Exponential Moving mean",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, sqrt(variance) AS std FROM \"moving_statistics\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND topic = '$topic'"
    }
   ]
  },
  {
   "title": "T-digest Quantiles ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 15 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \r\n  time,\r\n  min as min_value,\r\n  \"q1\",\r\n  \"median\",\r\n  \"q3\",\r\n  \"max\",\r\n  topic\r\nFROM \"quantiles\"\r\nWHERE \r\n  $__timeFilter(time)\r\n  AND time >= '2004-01-01T00:00:00Z'\r\n  AND topic = '$topic'\r\nORDER BY time\r\n"
    }
   ]
  }
 ]
}